---
# 1. Namespace para ELK
apiVersion: v1
kind: Namespace
metadata:
  name: elk

---
# 2. Elasticsearch Deployment + Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
        ports:
        - containerPort: 9200
        env:
        - name: discovery.type
          value: "single-node"
        - name: xpack.security.enabled
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elk
spec:
  type: NodePort
  selector:
    app: elasticsearch
  ports:
  - port: 9200
    targetPort: 9200
    nodePort: 30920

---
# 3. Kibana Deployment + Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:8.13.0
        ports:
        - containerPort: 5601
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch:9200"
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: elk
spec:
  type: NodePort
  selector:
    app: kibana
  ports:
  - port: 5601
    targetPort: 5601
    nodePort: 30561

---
# 4. Produto WebAPI Deployment + Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: produto-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: produto-api
  template:
    metadata:
      labels:
        app: produto-api
    spec:
      containers:
      - name: produto-api
        image: paulomauri/produto-api:1.0
        ports:
        - containerPort: 5000
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
---
apiVersion: v1
kind: Service
metadata:
  name: produto-api-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: produto-api
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32042
